debug: true
server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: http://somegitresource.git
          searchPaths: somfefolder
          username: ${BITBUCKET_USERNAME}
          password: ${BITBUCKET_PASSWORD}

AUTHENTICATION_API: http://someting:9909
